### ISSUE TITLE
v0.3.1 crash

### ISSUE THREAD

**Issue by gordelu** [Wynd/MineMineNoMi3#13]
When i start a minecraft server with mine mine no mi v0.3.1 the server crash, i tried to set this mod alone and still crashing please fixing it we cant use it well

**Comment by Wynd** [comment]
Sorry but....can you add some crashlogs either as file or paste them here https://pastebin.com/ ?
I can't do anything just with "server crashes"...

**Comment by gordelu** [comment]
ohh sorry i wrote badly, it crash with other mods not alone but can you help me to fix it? 
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 28/06/18 22:10
Description: Exception in server tick loop

java.lang.IllegalArgumentException: Duplicate enchantment id! class xyz.pixelatedw.MineMineNoMi3.MainEnchantment and class net.nevermine.assist.AscensionEnchants$1 Enchantment ID:100
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
	at xyz.pixelatedw.MineMineNoMi3.MainEnchantment.<init>(MainEnchantment.java:10)
	at xyz.pixelatedw.MineMineNoMi3.lists.ListEffects.init(ListEffects.java:14)
	at xyz.pixelatedw.MineMineNoMi3.MainMod.init(MainMod.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:713)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:323)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:286)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 568620080 bytes (542 MB) / 2126512128 bytes (2028 MB) up to 4660396032 bytes (4444 MB)
	JVM Flags: 2 total; -Xms1024M -Xmx5000M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.114.1388 Minecraft Forge 10.13.3.1403 26 mods loaded, 26 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	FML{7.10.114.1388} [Forge Mod Loader] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Forge{10.13.3.1403} [Minecraft Forge] (cauldron-1.7.10-2.1403.1.54-server.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	cuchaz.ships.core{1.7.10-1.0.3} [Ships Mod Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
	heart{2.0.0} [Heart Health] ([MC1.7.X]Hearts-2.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	nevermine{2.3} [AdventOfAscension] (AoA-2.4.B.jar) Unloaded->Constructed->Pre-initialized->Initialized
	ArchitectureCraft{1.7.2} [ArchitectureCraft] (ArchitectureCraft-1.7.2-mc1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	armourersWorkshop{1.7.10-0.42.5} [Armourer's Workshop] (Armourers-Workshop-1.7.10-0.42.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	plushieWrapper{0.0.0} [Plushie Wrapper] (Armourers-Workshop-1.7.10-0.42.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1548-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) Unloaded->Constructed->Pre-initialized->Initialized
	CarpentersBlocks{3.3.8.1} [Carpenter's Blocks] (Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_23.3.2016.jar) Unloaded->Constructed->Pre-initialized->Initialized
	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
	LotsOfFood{1.7.10} [Lots of Food] (Lots of Food-1.7.10 v7.jar) Unloaded->Constructed->Pre-initialized->Initialized
	maplecrafted{3.0} [MapleCrafted] (MapleCraft_1.0_ALPHA.jar) Unloaded->Constructed->Pre-initialized->Initialized
	mapleitems{14.0} [Maple Items] (MapleItems14.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized
	mineminenomi{0.3.1} [Mine Mine no Mi] (Mine Mine no Mi - 1.7.10 - 0.3.1.jar) Unloaded->Constructed->Pre-initialized->Errored
	cuchaz.cuchazinteractive{1.7.10-1.0} [Cuchaz Interactive] (shipsMod-v1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	cuchaz.ships{1.7.10-1.0.3} [Ships Mod] (shipsMod-v1.7.10-1.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
	flammpfeil.slashblade{mc1.7.10-r87} [SlashBlade] (SlashBlade-mc1.7.10-r87.jar) Unloaded->Constructed->Pre-initialized->Initialized
	wylib{1.0} [WyLib] (WyLib 1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)


i think some mod is not workin with mine mine no mi but idk what is it

**Comment by Wynd** [comment]
Yes it's an id conflict but I'm not sure with which mod...if the other mod has a config you can change them there..otherwise wait until tomorrow, MMnM 0.3.2 will have id configs

**Comment by gordelu** [comment]
Can i have the link for 0.3.2 version?
