### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by aminimon1** [Wynd/MineMineNoMi3#27]
Hi. Everytime I try to start the game with the mod the game just crashes and shows me this:

The game crashed whilst initializing game
Error: java.lang.IllegalArgumentException: Duplicate enchantment id! class xyz.pixelatedw.MineMineNoMi3.MainEnchantment and class noppes.npcs.enchants.EnchantDamage Enchantment ID:100

Thanks in advance.

**Comment by Wynd** [comment]
Morning,

It's an easy fix really, in your .minecraft folder you should have a config folder go in it and open the mineminenomi.cfg file in here you need to edit these 2 lines

```
I:"Enchantment ID : Dial Impact"=100
I:"Enchantment ID : Kairoseki"=101

```

Change the numbers from 100/101 to pretty much any number between 63 (below it there are vanilla ids) and 255 until the crash is gone.

**Comment by aminimon1** [comment]
I have been trying that for a while but it doesn't seem to work. Is there a way to shorten the number down.


Sorry to be bothering you again

**Comment by Wynd** [comment]
Honestly it must work, if the crash persists then probably you don't have the correct config (maybe from an older version or something), I'm not sure which ids custom npcs uses, but trying 200/201 should work for example, maybe you have more mods that uses different ids however in which case you just need to find some empty spots

**Comment by aminimon1** [comment]
Do you have any advice on were I should check first?

**Comment by Wynd** [comment]
Just check the crash and see what id is conflicting like in your original id
'Enchantment ID:100'

**Comment by aminimon1** [comment]
From what I can tell nothing has changed.

**Comment by aminimon1** [comment]
I can send you the crash report if you like.

**Comment by Wynd** [comment]
Yes please, also just to be sure :
1. Delete your mineminenomi.cfg
2. Open MC and let it create a new cfg
3. Change it again and try it again

**Comment by aminimon1** [comment]
I tried to delete it but everything was the same.

**Comment by aminimon1** [comment]
And here is whole crash report:

--
// Why did you do that?

Time: 2018-09-30 16:55
Description: Initializing game

java.lang.IllegalArgumentException: Duplicate enchantment id! class xyz.pixelatedw.MineMineNoMi3.MainEnchantment and class noppes.npcs.enchants.EnchantDamage Enchantment ID:100
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
	at xyz.pixelatedw.MineMineNoMi3.MainEnchantment.<init>(MainEnchantment.java:10)
	at xyz.pixelatedw.MineMineNoMi3.lists.ListEffects.init(ListEffects.java:15)
	at xyz.pixelatedw.MineMineNoMi3.MainMod.init(MainMod.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:53)
	at xyz.pixelatedw.MineMineNoMi3.MainEnchantment.<init>(MainEnchantment.java:10)
	at xyz.pixelatedw.MineMineNoMi3.lists.ListEffects.init(ListEffects.java:15)
	at xyz.pixelatedw.MineMineNoMi3.MainMod.init(MainMod.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 88349768 bytes (84 MB) / 352321536 bytes (336 MB) up to 1073741824 bytes (1024 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 22 mods loaded, 22 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHI	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHI	AncientWarfare{2.4.114-beta-MC1.7.10} [Ancient Warfare Core] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHI	AncientWarfareAutomation{2.4.114-beta-MC1.7.10} [Ancient Warfare Automation] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHI	AncientWarfareNEIPlugin{2.4.114-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHI	AncientWarfareNpc{2.4.114-beta-MC1.7.10} [Ancient Warfare NPCs] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHI	AncientWarfareStructure{2.4.114-beta-MC1.7.10} [Ancient Warfare Structures] (Ancient-Warfare-Mod-1.7.10.jar) 
	UCHI	examplemod{1.0} [Example Mod] (Avatar TLB 0.7.4.jar) 
	UCHI	kieranvs_avatar{0.7.4} [Avatar] (Avatar TLB 0.7.4.jar) 
	UCHI	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar) 
	UCHI	customnpcs{1.7.10d} [CustomNpcs] (Custom-NPCs-Mod-1.7.10.jar) 
	UCHI	DamageIndicatorsMod{3.2.0} [Damage Indicators] (Damage-Indicators-Mod-1.7.10 (1).jar) 
	UCHI	Project_Alchemy{1.0.15} [FullThrottle Alchemist] (FullThrottle_Alchemist-1.7.10-1.0.15.jar) 
	UCHI	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
	UCHI	journeymap{5.1.4p1} [JourneyMap] (journeymap-1.7.10-5.1.4p1-unlimited.jar) 
	UCHI	lootbags{2.0.17} [Loot Bags] (LootBags-1.7.10-2.0.17.jar) 
	UCHE	mineminenomi{0.3.2} [Mine Mine no Mi] (Mine Mine no Mi - 1.7.10 - 0.3.2.jar) 
	UCHI	AM{1.0.0} [Naruto Mod] (Naruto-Anime-Mod_V0.9.17_Beta_1.7.10-1.0.jar) 
	UCHI	fiskheroes{1.0.13} [Fisk's Superheroes] (Superheroes-Mod-by-FiskFille-1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13

**Comment by Wynd** [comment]
Yeah...clearly the id doesn't change...you're sure you're changing the id from the correct config ? 
.minecraft/config/mineminenomi.cfg ?

**Comment by aminimon1** [comment]
I think so

**Comment by aminimon1** [comment]
I went into the config and into the mineminenomi code writer

**Comment by aminimon1** [comment]
Here is everything in the code writer:

# Configuration file

general {
    B:"Allow Devil Fruits to drop from leaves"=true
    B:"Allow Logia Invulnerability"=true
    B:"Allow Ships to Spawn"=true
    S:"Keep stats after death"=auto
    I:"Modifier for Spawning Ships"=1
    D:"Rate at which Devil Fruits drop from leaves"=1
    B:"Receive Extra Hearts"=true
}


ids {
    I:"Enchantment ID : Dial Impact"=200
    I:"Enchantment ID : Kairoseki"=201
}


"mine mine no mi config" {
    B:"Allow 3D Rendering"=false
    B:"Allow Debug Mode"=false
    B:"Allow Griefing"=true
    B:"Allow Particles"=true
    B:"Allow Quests"=true
    B:"Allow Quests [WIP]"=true
    B:"Allow Race/Faction"=true
    B:"Allow Race/Faction [WIP]"=true
    B:"Allow Ships Spawn"=true
    B:"Allow Sounds"=false
    B:"Reset Stats After Death"=true
}


permissions {
    S:"Ability Restrictions" <
        example1
        example2
     >
    I:"Permission : /belly"=2
    I:"Permission : /bounty"=2
    I:"Permission : /doriki"=2
    I:"Permission : /extol"=2
    I:"Permission : /removedf"=2
}


system {
    B:"Allow FOV Modifiers"=false
    B:"Allow Telemetry"=true
    B:"Allow Update Message"=true
}

**Comment by aminimon1** [comment]
I'll see if I can fix it in any way. Anyways Thanks.

**Comment by aminimon1** [comment]
Hi. Just wanted to tell you that I got it to work.

**Comment by Wynd** [comment]
Awesome, glad you've fixed it ^^ thanks for saying it as well
