### ISSUE TITLE
 I want to get your permission to carry and translate this mod to MCBBS（china）

### ISSUE THREAD

**Issue by AkumaLeo** [Wynd/MineMineNoMi3#4]
it's a nice mod .I really want to install in server and play with my friends, but it still some bugs,
I hope you can update MOD as soon as possible

**Comment by AkumaLeo** [comment]
encounter fatal error in server

[16:10:24 ERROR]: Fatal errors were detected during the transition from INITIALIZATION to POSTINITIALIZATION. Loading cannot continue
[16:10:24 ERROR]: 
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (KCauldron-1.7.10-1
614.201.jar) 
	UCHI	Forge{10.13.4.1614} [Minecraft Forge] (KCauldron-1.7.10-1614.201.jar) 
	UCHI	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHE	mineminenomi{0.3.0} [Mine Mine no Mi] (Mine Mine no Mi-1.7.10-0.3.0 dev build #4.jar) 
[16:10:24 ERROR]: The following problems were captured during this phase
[16:10:24 ERROR]: Caught exception from mineminenomi
java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at MineMineNoMi3.Lists.ListDevilFruits.init(ListDevilFruits.java:63) ~[ListDevilFruits.class:?]
	at MineMineNoMi3.Main.init(Main.java:52) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorI
mpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.Nativ
eMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown
 Source) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]

	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~
[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.cl
ass:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_
51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(Synchronized
EventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.com
mon.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:73
7) [Loader.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) [FMLServerHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325) [FML
CommonHandler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [MinecraftServer.class:?]
	at java.lang.Thre
ad.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.lo
adClass(Unknown Source) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
	... 34 more
Caused by: java.lang.RuntimeException: Attempted to load class bdw for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransfo
rmer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassL
oader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
	... 34 more
[16:10:24 ERROR]: Encountered an unexpected
 exception
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen

	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739) ~[Loader.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97) ~[FMLServerHandler.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.FMLCommonHandler.onServer
Started(FMLCommonHandler.java:325) ~[FMLCommonHandler.class:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631) [Mi
necraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
	at MineMineNoMi3.Lists.ListDevilFruits.init(ListDevilFruits.java:63) ~[ListDevilFruits.class:?]
	at Mine
MineNoMi3.Main.init(Main.java:52) ~[Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Un
known Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccess
orImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:
1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.goog
le.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.1
0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-R0
.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.
lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscrib
er.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.
EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.
class:1.7.10-R0.1-SNAPSHOT]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoade
r.loadClass(Unknown Source) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
	at MineMineNoMi3.Lists.ListDevilFruits.init(ListDevilFruits.java:63) ~[ListDevilFruits.class:?]
	at MineMineNoMi3.Main.init(Main.java:52) ~[Main.class:
?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.refle
ct.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) ~[FMLModContainer.class:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at
 sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_51]
	at com.google.common.eventbus.EventS
ubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.j
ava:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.10.jar:?]
	at cpw.mods.fml.common.LoadController
.sendEventToModContainer(LoadController.java:212) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at sun.reflect.NativeMethodAccess
orImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:
1.8.0_51]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[server-1.7.10.jar:?]
	at com.goog
le.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[server-1.7.10.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[server-1.7.1
0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) ~[LoadController.class:1.7.10-R0.1-SNAPSHOT]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) ~[Loader.class:1.7.10-R0.1-SNAPSHOT]
	... 5 more
Caused 
by: java.lang.RuntimeException: Attempted to load class bdw for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51) ~[KCauldron-1.7.10-1614.201.jar:1.7.10-R0.1-SNAPSHOT]
	at net.minecraft.launchwrappe
r.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) 
~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_51]
	at MineMineNoMi3.Lists.ListDevilFruits.init(ListDevilFruits.java:63) ~[ListDevilFruits.class:?]
	at MineMineNoMi3.Main.init(Main.java:52) ~[Main.class:?]
	at sun.reflect.NativeMet
hodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Unknown Sou

**Comment by Wynd** [comment]
Thanks :) the mod is still in development but don't worry most bugs were fixed, the one you've just reported as well, as for the translation stuff go ahead.
