### ISSUE TITLE
About opening the server

### ISSUE THREAD

**Issue by SaoPig2333** [Wynd/MineMineNoMi3#55]
Hello, the author, first of all, thank you for making this mod. many people like it in China. thank you very much. But I have a problem. When I use this MOD to open the server, if I use this MOD to open the server, the player can enter, but if I add another MOD, the player will always display the downloaded map when entering the server. Finally, the connection fails. I hope it can be solved. Thank you.

**Comment by Wynd** [comment]
Hi, glad to hear it's popular there too...I'm not 100% sure what you're talking about and without a crashlog, or a list of mods that you have on the server I can't really do anything, there are plenty of other guys with servers or modpacks, and they don't have a single problem. So I'm not sure why this is a thing in your case.

**Comment by SaoPig2333** [comment]
This is my mistake, thank you! ! !




tream0(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.access$20
0(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unk
nown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unk
nown Source)
[22:07:12 WARN]:        at java.security.AccessController.doPrivileged(Native Me
thod)
[22:07:12 WARN]:        at java.security.AccessController.doPrivilegedWithCombin
er(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.get
InputStream(Unknown Source)
[22:07:12 WARN]:        at java.net.URL.openStream(Unknown Source)
[22:07:12 WARN]:        at xyz.pixelatedw.MineMineNoMi3.events.EventsPersistence
.onEntityJoinWorld(EventsPersistence.java:821)
[22:07:12 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_69_E
ventsPersistence_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
[22:07:12 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invo
ke(ASMEventHandler.java:54)
[22:07:12 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventB
us.java:140)
[22:07:12 WARN]:        at net.minecraft.world.World.addEntity(World.java:1865)
[22:07:12 WARN]:        at net.minecraft.world.World.func_72838_d(World.java:176
5)
[22:07:12 WARN]:        at net.minecraft.server.management.ServerConfigurationMa
nager.func_72377_c(ServerConfigurationManager.java:386)
[22:07:12 WARN]:        at net.minecraft.server.management.ServerConfigurationMa
nager.initializeConnectionToPlayer(ServerConfigurationManager.java:223)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatch
er.completeServerSideConnection(NetworkDispatcher.java:200)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatch
er.completeHandshake(NetworkDispatcher.java:475)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeComplet
ionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeComplet
ionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[22:07:12 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelR
ead(SimpleChannelInboundHandler.java:98)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeC
hannelRead(DefaultChannelHandlerContext.java:337)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireCha
nnelRead(DefaultChannelHandlerContext.java:323)
[22:07:12 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channe
lRead(MessageToMessageDecoder.java:103)
[22:07:12 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelR
ead(MessageToMessageCodec.java:111)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeC
hannelRead(DefaultChannelHandlerContext.java:337)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireCha
nnelRead(DefaultChannelHandlerContext.java:323)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRe
ad(DefaultChannelPipeline.java:785)
[22:07:12 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInboun
d(EmbeddedChannel.java:169)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.f
unc_148833_a(FMLProxyPacket.java:77)
[22:07:12 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(Net
workManager.java:245)
[22:07:12 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(Net
workSystem.java:173)
[22:07:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(Min
ecraftServer.java:1023)
[22:07:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_7
1190_q(DedicatedServer.java:432)
[22:07:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(Min
ecraftServer.java:841)
[22:07:12 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:693)
[22:07:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:07:12 WARN]: [AutoSaveWorld] Something attempted to access socket://dl.dropb
oxusercontent.com:443 in main server thread, printing stack trace
[22:07:12 WARN]: java.lang.Exception: Stack trace
[22:07:12 WARN]:        at java.lang.Thread.dumpStack(Unknown Source)
[22:07:12 WARN]:        at autosaveworld.modules.networkwatcher.NetworkWatcherPr
oxySelector.select(NetworkWatcherProxySelector.java:57)
[22:07:12 WARN]:        at java.net.SocksSocketImpl.connect(Unknown Source)
[22:07:12 WARN]:        at java.net.Socket.connect(Unknown Source)
[22:07:12 WARN]:        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source
)
[22:07:12 WARN]:        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown So
urce)
[22:07:12 WARN]:        at sun.net.NetworkClient.doConnect(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.http.HttpClient.openServer(Unknown Source
)
[22:07:12 WARN]:        at sun.net.www.http.HttpClient.openServer(Unknown Source
)
[22:07:12 WARN]:        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown
 Source)
[22:07:12 WARN]:        at sun.net.www.protocol.https.HttpsClient.New(Unknown So
urce)
[22:07:12 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLCo
nnection.getNewHttpClient(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConn
ect0(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unk
nown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unk
nown Source)
[22:07:12 WARN]:        at java.security.AccessController.doPrivileged(Native Me
thod)
[22:07:12 WARN]:        at java.security.AccessController.doPrivilegedWithCombin
er(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConn
ect(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLCo
nnection.connect(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream0(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.access$20
0(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unk
nown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unk
nown Source)
[22:07:12 WARN]:        at java.security.AccessController.doPrivileged(Native Me
thod)
[22:07:12 WARN]:        at java.security.AccessController.doPrivilegedWithCombin
er(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream(Unknown Source)
[22:07:12 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.get
InputStream(Unknown Source)
[22:07:12 WARN]:        at java.net.URL.openStream(Unknown Source)
[22:07:12 WARN]:        at xyz.pixelatedw.MineMineNoMi3.events.EventsPersistence
.onEntityJoinWorld(EventsPersistence.java:821)
[22:07:12 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_69_E
ventsPersistence_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
[22:07:12 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invo
ke(ASMEventHandler.java:54)
[22:07:12 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventB
us.java:140)
[22:07:12 WARN]:        at net.minecraft.world.World.addEntity(World.java:1865)
[22:07:12 WARN]:        at net.minecraft.world.World.func_72838_d(World.java:176
5)
[22:07:12 WARN]:        at net.minecraft.server.management.ServerConfigurationMa
nager.func_72377_c(ServerConfigurationManager.java:386)
[22:07:12 WARN]:        at net.minecraft.server.management.ServerConfigurationMa
nager.initializeConnectionToPlayer(ServerConfigurationManager.java:223)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatch
er.completeServerSideConnection(NetworkDispatcher.java:200)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatch
er.completeHandshake(NetworkDispatcher.java:475)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeComplet
ionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeComplet
ionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[22:07:12 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelR
ead(SimpleChannelInboundHandler.java:98)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeC
hannelRead(DefaultChannelHandlerContext.java:337)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireCha
nnelRead(DefaultChannelHandlerContext.java:323)
[22:07:12 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channe
lRead(MessageToMessageDecoder.java:103)
[22:07:12 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelR
ead(MessageToMessageCodec.java:111)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeC
hannelRead(DefaultChannelHandlerContext.java:337)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireCha
nnelRead(DefaultChannelHandlerContext.java:323)
[22:07:12 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRe
ad(DefaultChannelPipeline.java:785)
[22:07:12 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInboun
d(EmbeddedChannel.java:169)
[22:07:12 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.f
unc_148833_a(FMLProxyPacket.java:77)
[22:07:12 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(Net
workManager.java:245)
[22:07:12 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(Net
workSystem.java:173)
[22:07:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(Min
ecraftServer.java:1023)
[22:07:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_7
1190_q(DedicatedServer.java:432)
[22:07:12 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(Min
ecraftServer.java:841)
[22:07:12 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:693)
[22:07:12 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:07:33 WARN]: java.net.ConnectException: Connection timed out: connect
[22:07:33 WARN]:        at java.net.TwoStacksPlainSocketImpl.socketConnect(Nativ
e Method)
[22:07:33 WARN]:        at java.net.AbstractPlainSocketImpl.doConnect(Unknown So
urce)
[22:07:33 WARN]:        at java.net.AbstractPlainSocketImpl.connectToAddress(Unk
nown Source)
[22:07:33 WARN]:        at java.net.AbstractPlainSocketImpl.connect(Unknown Sour
ce)
[22:07:33 WARN]:        at java.net.PlainSocketImpl.connect(Unknown Source)
[22:07:33 WARN]:        at java.net.SocksSocketImpl.connect(Unknown Source)
[22:07:33 WARN]:        at java.net.Socket.connect(Unknown Source)
[22:07:33 WARN]:        at sun.security.ssl.SSLSocketImpl.connect(Unknown Source
)
[22:07:33 WARN]:        at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown So
urce)
[22:07:33 WARN]:        at sun.net.NetworkClient.doConnect(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.http.HttpClient.openServer(Unknown Source
)
[22:07:33 WARN]:        at sun.net.www.http.HttpClient.openServer(Unknown Source
)
[22:07:33 WARN]:        at sun.net.www.protocol.https.HttpsClient.<init>(Unknown
 Source)
[22:07:33 WARN]:        at sun.net.www.protocol.https.HttpsClient.New(Unknown So
urce)
[22:07:33 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLCo
nnection.getNewHttpClient(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConn
ect0(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unk
nown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$6.run(Unk
nown Source)
[22:07:33 WARN]:        at java.security.AccessController.doPrivileged(Native Me
thod)
[22:07:33 WARN]:        at java.security.AccessController.doPrivilegedWithCombin
er(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConn
ect(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLCo
nnection.connect(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream0(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.access$20
0(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unk
nown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection$9.run(Unk
nown Source)
[22:07:33 WARN]:        at java.security.AccessController.doPrivileged(Native Me
thod)
[22:07:33 WARN]:        at java.security.AccessController.doPrivilegedWithCombin
er(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputS
tream(Unknown Source)
[22:07:33 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.get
InputStream(Unknown Source)
[22:07:33 WARN]:        at java.net.URL.openStream(Unknown Source)
[22:07:33 WARN]:        at xyz.pixelatedw.MineMineNoMi3.events.EventsPersistence
.onEntityJoinWorld(EventsPersistence.java:821)
[22:07:33 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler_69_E
ventsPersistence_onEntityJoinWorld_EntityJoinWorldEvent.invoke(.dynamic)
[22:07:34 WARN]:        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invo
ke(ASMEventHandler.java:54)
[22:07:34 WARN]:        at cpw.mods.fml.common.eventhandler.EventBus.post(EventB
us.java:140)
[22:07:34 WARN]:        at net.minecraft.world.World.addEntity(World.java:1865)
[22:07:34 WARN]:        at net.minecraft.world.World.func_72838_d(World.java:176
5)
[22:07:34 WARN]:        at net.minecraft.server.management.ServerConfigurationMa
nager.func_72377_c(ServerConfigurationManager.java:386)
[22:07:34 WARN]:        at net.minecraft.server.management.ServerConfigurationMa
nager.initializeConnectionToPlayer(ServerConfigurationManager.java:223)
[22:07:34 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatch
er.completeServerSideConnection(NetworkDispatcher.java:200)
[22:07:34 WARN]:        at cpw.mods.fml.common.network.handshake.NetworkDispatch
er.completeHandshake(NetworkDispatcher.java:475)
[22:07:34 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeComplet
ionHandler.channelRead0(HandshakeCompletionHandler.java:21)
[22:07:34 WARN]:        at cpw.mods.fml.common.network.internal.HandshakeComplet
ionHandler.channelRead0(HandshakeCompletionHandler.java:11)
[22:07:34 WARN]:        at io.netty.channel.SimpleChannelInboundHandler.channelR
ead(SimpleChannelInboundHandler.java:98)
[22:07:34 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeC
hannelRead(DefaultChannelHandlerContext.java:337)
[22:07:34 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireCha
nnelRead(DefaultChannelHandlerContext.java:323)
[22:07:34 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channe
lRead(MessageToMessageDecoder.java:103)
[22:07:34 WARN]:        at io.netty.handler.codec.MessageToMessageCodec.channelR
ead(MessageToMessageCodec.java:111)
[22:07:34 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.invokeC
hannelRead(DefaultChannelHandlerContext.java:337)
[22:07:34 WARN]:        at io.netty.channel.DefaultChannelHandlerContext.fireCha
nnelRead(DefaultChannelHandlerContext.java:323)
[22:07:34 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRe
ad(DefaultChannelPipeline.java:785)
[22:07:34 WARN]:        at io.netty.channel.embedded.EmbeddedChannel.writeInboun
d(EmbeddedChannel.java:169)
[22:07:34 WARN]:        at cpw.mods.fml.common.network.internal.FMLProxyPacket.f
unc_148833_a(FMLProxyPacket.java:77)
[22:07:34 WARN]:        at net.minecraft.network.NetworkManager.func_74428_b(Net
workManager.java:245)
[22:07:34 WARN]:        at net.minecraft.network.NetworkSystem.func_151269_c(Net
workSystem.java:173)
[22:07:34 WARN]:        at net.minecraft.server.MinecraftServer.func_71190_q(Min
ecraftServer.java:1023)
[22:07:34 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_7
1190_q(DedicatedServer.java:432)
[22:07:34 WARN]:        at net.minecraft.server.MinecraftServer.func_71217_p(Min
ecraftServer.java:841)
[22:07:34 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftSer
ver.java:693)
[22:07:34 WARN]:        at java.lang.Thread.run(Unknown Source)
[22:07:34 INFO]: Sao_Pig lost connection: Disconnected
[22:07:34 INFO]: Sao_Pig left the game.

**Comment by Wynd** [comment]
Fixed in 0.5.0
